
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermanagement?useSSL=false&serverTimezone=UTC
    username: root
    password: 0786261@Kin!
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 1000


logging:
  level:
    com.api.user: DEBUG

  security:
    user:
      name: admin
      password: admin